### PR TITLE
Main Menu Work mk.2

### PR DESCRIPTION
**Pull request by ResidentBiscuit**
Trying this again since #80 broke.

### CODE REVIEW

**Comment by ResidentBiscuit** [comment]
I just realized that this is still on the monospace font

**Comment by LB--** [comment]
I think all it needs now is documentation :+1:

**Comment by ResidentBiscuit** [comment]
And the position of Start and Quit are are a little weird. I can't get them to center nicely.

**Comment by LB--** [comment]
I'll see what can be done about the alignment - I had some code before that did it before #80 was made.

**Comment by LB--** [comment]
Check out https://github.com/cpluspluscom/ChessPlusPlus/commit/e31ba94a94aa779e94de7152a65e1362079a06a9 (it's in this repo's `rb-menu` branch)

By the way, the contributing guidelines say to use 4 spaces per indent, not tabs.

**Comment by ResidentBiscuit** [comment]
> By the way, the contributing guidelines say to use 4 spaces per indent, not tabs.

Bullocks, I forgot about this. I'll get these converted.

**Comment by ResidentBiscuit** [comment]
Tabs have been converted to spaces.

**Comment by LB--** [comment]
What about https://github.com/cpluspluscom/ChessPlusPlus/commit/e31ba94a94aa779e94de7152a65e1362079a06a9 ?

**Comment by ResidentBiscuit** [comment]
Merged your text centering work into this branch.

**Comment by LB--** [comment]
Hmm, something about the merge messed up the indentation in various places. I'll try to fix it when I merge it tomorrow. I'm not at my computer atm.

**Pull request merged**
