### PR TITLE
Updated Travis & Rewritten CMake

### PR DESCRIPTION
**Pull request by LB--**
So, a lot of time has gone by, and in that time I have learned a lot more about CMake. Also in that time, Travis has deprecated the infrastructure we were using and moved to a container-based infrastructure via Docker which doesn't yet support `sudo`. So, I rewrote the CMake stuff using the knowledge I now have about CMake, and I redid the Travis script to no longer run on the legacy infrastructure. Travis supports caching now, so although we still need to build SFML and Boost manually, they can be cached so that future builds run much faster.

**Please test the new CMake build on your systems!** I don't have access to Mac/OSX, so I can only test on my own Windows 10 and whatever systems Travis has. Currently Travis tests with GCC 5.1 and Clang 3.8 on Ubuntu. Travis supports OSX too but I have no idea how that works - I'll be doing a separate PR for that because it's another huge undertaking (more research, trial, and error, repeat).

Remember that if you don't have SFML and Boost installed to standard locations, you will definitely need to pass `-DSFML_ROOT=path` and `-DBOOST_ROOT=path` to CMake. If you want to use static linking with SFML, pass `-DSFML_STATIC_LIBRARIES=ON` to CMake as well (and similarly if you build Boost statically with MSVC, pass `-DBoost_USE_STATIC_LIBS=ON` to CMake). If you want hints about the general build process, read the Travis script. Make sure you're using the latest version of your preferred compiler for your system that you can. If you need to build Boost yourself, you can save time by only building `--with-system --with-filesystem` because that's all that is required by ChessPlusPlus currently.

I have tested with nuwen MinGW 5.1.0 (works very well) and Visual Studio 2015 (everything compiles, but Boost 1.59 is completely broken and tries to link to 1.58 lib files when linking ChessPlusPlus - maybe the Boost devs don't even know VS2015 exists?).

Things I will be doing in separate PRs:
* Adding OSX support on Travis
* Getting CMake to build SFML for you with [CMake External Projects](https://cmake.org/cmake/help/latest/module/ExternalProject.html)

After all that is out of the way I'll start tackling the other issues (separating client and server logic for multiplayer, adding unit tests, etc.) - though no promises as to the timely nature of these things.

### CODE REVIEW

**Comment by ResidentBiscuit** [comment]
Can you squash some (or all) of those commits? Other than that, it looks good. I can test on Ubuntu 14.04 later today (I believe travis runs 12.04 still). We might enlist the help of @usandfriends or @TheRabbitologist to make sure it builds fine on OS X.

**Comment by LB--** [comment]
I meant to squash them but forgot, it's done now.

**Comment by usandfriends** [comment]
Just built fine without any warnings using:
+ OS X 10.11.1
+ CMake 3.3.1
+ GNU Make 3.81

**Comment by LB--** [comment]
@usandfriends did you try building the Mac Bundle? Pass `-DBUILD_APPBUNDLE=ON` to CMake. Also, try using the XCode generator instead of the makefiles generator.

**Comment by usandfriends** [comment]
I ran `cmake -DBUILD_APPBUNDLE=ON -G Xcode` and built the product on XCode successfully. However, opening the product (`.app`) gave `resource missing` errors as the resources were not bundled within the app.

**Comment by LB--** [comment]
@usandfriends weird, I didn't change that part of the CMake script very much, so I don't know what's broken. Are you able to view the contents of the .app to see where the `res/` and `config/` folders ended up (or if they are even there)? It might be that they are there and that the way we are loading files in the code is the issue, but I don't really know.

**Comment by usandfriends** [comment]
@LB-- `res` is copied into `chesspp.app/Contents/Resources/` as `chesspp.app/Contents/Resources/res`

**Comment by LB--** [comment]
@usandfriends The executable path is where it thinks the executable is located, which isn't always the same as where the working directory is. ChessPlusPlus tries to load from the working directory, not the directory the executable is in. I'll add another commit that also prints the working directory to the log so we can investigate that.

**Comment by usandfriends** [comment]
@LB-- Here's the output:

    [18:30:31] Executable path   = "/me/GitHub/ChessPP_LB/build/Debug/ChessPlusPlus.app/Contents/MacOS/../Resources/"
    [18:30:31] Working directory = "/me/GitHub/ChessPP_LB/build/Debug"
    [18:30:31] N7chesspp9ExceptionE caught in main: stream given to JsonReader in bad state

**Comment by LB--** [comment]
@usandfriends I see, so this is something that has always been broken and was just never noticed before. I'll fix it in another PR - for now, just make sure the directory containing the .app bundle also contains the res/ and config/ folders (you can copy them manually).

**Comment by usandfriends** [comment]
@LB-- Sure, thank you for looking into this.

**Comment by LB--** [comment]
@ResidentBiscuit did your Ubuntu build go well? If so it should be safe to merge this.

**Comment by ResidentBiscuit** [comment]
Oh yeah, whoops. All was well.
Ubuntu 14.04
G++ 5.1
SFML2.x
Don't recall my Boost version but I think 1.57

I can get better version numbers when I get home, but yeah I say it's safe to merge.

**Pull request merged**
